
# ░█████╗░██╗░░░██╗████████╗░█████╗░░░░░░░████████╗██╗░░░██╗███╗░░██╗███████╗
# ██╔══██╗██║░░░██║╚══██╔══╝██╔══██╗░░░░░░╚══██╔══╝██║░░░██║████╗░██║██╔════╝
# ███████║██║░░░██║░░░██║░░░██║░░██║█████╗░░░██║░░░██║░░░██║██╔██╗██║█████╗░░
# ██╔══██║██║░░░██║░░░██║░░░██║░░██║╚════╝░░░██║░░░██║░░░██║██║╚████║██╔══╝░░
# ██║░░██║╚██████╔╝░░░██║░░░╚█████╔╝░░░░░░░░░██║░░░╚██████╔╝██║░╚███║███████╗
# ╚═╝░░╚═╝░╚═════╝░░░░╚═╝░░░░╚════╝░░░░░░░░░░╚═╝░░░░╚═════╝░╚═╝░░╚══╝╚══════╝

##  -- Auto-Tune Config File --  ##

## See the wiki for info on each setting: https://github.com/Unprotesting/Auto-Tune/wiki

##  -- General Settings --  ##

##  Enable/Disable integrated Web Server.
##  Info: Use /trade to view the web-server
web-server-enabled: true

##  Port for integrated Web Server (If enabled)
##  Make sure to port-forward and disable firewalls for this port.
port: 8123

##  Time Period in minutes
##  Info: When decreasing or increasing this adjust your volatility settings accordingly
time-period: 30

##  GUI Shop Menu title
menu-title: 'Shop'

##  GUI Shop Menu background
##  Info: Use 'NONE' for no background
background: 'BLACK_STAINED_GLASS_PANE'

##  How often auto-sell updates in ticks
##  Info: Set this higher if few players use autosell
##  Info: Set it lower if many players use autosell
auto-sell-update-period: 10

##  How often players are shown their auto-sell profits in ticks
auto-sell-profit-update-period: 600

##  Global number format
number-format: '###,###,###,###,##0.00'

##  Enable Enchantments
enable-enchantments: true

##  -- Pricing Model Settings --  ##

##  Percentage difference in sell price to buy price
sell-price-difference: 15.0

##  Maximum Volatility per Time Period for the Variable Volatility price calculation algorithm as a percentage of total price
max-volatility: 0.5

##  Minimum Volatility per Time Period for the Fixed Volatility price calculation algorithm in economy units
min-volatility: 0.05

##  -- Data Selection Settings --  ##

##  Info: When setting your data selection algorithm use a site such as https://www.desmos.com/calculator
##  Info: Data selection uses the equation y=m(x^z)+c, for example the default is y=0.075(x^(1.6))+0.55

##  'm' in equation: y=m(x^z)+c
data-selection-m: 0.05

##  'z' in equation: y=m(x^z)+c
data-selection-z: 1.75

##  'c' in equation: y=m(x^z)+c
data-selection-c: 0.55

##  -- Other Economy Settings --

##  Minimum players needed, to be online, for prices to update
##  Info: It is recommended to keep this above 0
update-prices-threshold: 1

##  The symbol that appears before all currency
currency-symbol: '$'

##  Enable sell price difference variation to ease out sell price variation
sell-price-difference-variation-enabled: true

##  Starting percentage sell price difference for sell price variation
sell-price-difference-variation-start: 30.0

##  Time in minutes until sell price reaches sell-price-difference set in pricing model settings (default 4 weeks)
sell-price-variation-time-period: 43200

##  Time in minutes that the sell-price-difference updates
sell-price-variation-update-period: 30

##  Interest rate per interest-rate-update-period
##  Info: This is the increase in the current debt payment per-time period
interest-rate: 0.05

##  Time period in ticks between updates of the interest rate for users loans
interest-rate-update-period: 1200

##  Disable the max-buy/max-sells for items
##  Info: Don't do this unless you know what your doing.
##  Info: If this is enabled, it is likely to lead to exploitation on servers with under 10 concurrent players
disable-max-buys-sells: false

##  The lowest value in $ a player can go into debt
##  For example if a player has $3,000 and this is set to 1000 a player can take out a loan up to $2,000
max-debt-value: 1000.0

##  The percentage value to decrease items sold with enchantments
##  Info: This value should be above 0 because it limits the exploit-ability of enchantments
##  Info: This doesn't affect the buy-price.
enchantment-limiter: 10.0

##  The percentage value to decrease items sold with a loss in durability
##  Info: This is applied ON TOP of the durability algorithm to limit the exploit-ability of selling tools
durability-limiter: 15.0

##  -- Other Settings --

##  Ignore AFK players in price calculations/online checks
##  Info: Turning this on will mean the price will only update when there's a player that is not AFK
##  Info: This only applies to essentials AFK and you must have essentials installed for this to work
ignore-afk: true

##  Enable the Auto-Tune tutorial for players (the messages that are displayed to players periodically)
##  Keep this on to encourage purchasing turn it off if it is distracting
tutorial: true

##  Time in seconds between messages
tutorial-message-period: 360

##  Data storage location
data-location: 'plugins/Auto-Tune/'

##  The level of the logger to use
##  Info: This is the level of logging that is outputted to the console
##  Info: Possible values are: SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST
log-level: 'INFO'
