##################################################
###                                            ###
##########       <-- Auto-Tune -->       #########
###                                            ###
##################################################


##  -- General Settings --  ##

##  Enable//Disable integrated Web Server.
web-server-enabled: true

##  Port for integrated Web Server (If enabled and on correct plan)
port: 8123

##  Server name that will show up in commands and requests
server-name: 'Auto-Tune Test Server'

##  Automatic Pricing Model
pricing-model: 'Basic'

##  Time Period in minutes
time-period: 10

##  The amount of menu rows in the GUI shop, minimum is 3
menu-rows: 6

##  GUI Shop Menu title
menu-title: 'Auto-Tune Shop'

##  Message sent for players with no permission
no-permission: 'You do not have permission to perform this command'

##  -- Basic Pricing Model Settings --  ##

##  Volatility Calulation Algorithim
##  Info: A fixed rate locks the maxiumum change to a certain price
##  Info: A variable rate changes the maxiumum price-change based on current price calculations
Basic-Volatility-Algorithim: 'Fixed'

##  Percentage difference in sell price to buy price
sell-price-difference: 2.5

##  Maximum Volatility per Time Period for the Fixed Volatility price calculation algorithim in economy units
Basic-Fixed-Max-Volatility: 2.00

##  Maximum Volatility per Time Period for the Variable Volatility price calculation algorithim as a percentage of total price
Basic-Variable-Max-Volatility: 6.00

##  Minimum Volatility per Time Period for the Fixed Volatility price calculation algorithim in economy units
Basic-Fixed-Min-Volatility: 0.05

##  Minimum Volatility per Time Period for the Variable Volatility price calculation algorithim as a percentage of total price
Basic-Variable-Min-Volatility: 0.15

##  -- Other settings --
debug-enabled: false










