##################################################
###                                            ###
##########       <-- Auto-Tune -->       #########
###                                            ###
##################################################


##  -- General Settings --  ##

##  Enable//Disable integrated Web Server.
web-server-enabled: true

##  Port for integrated Web Server (If enabled and on correct plan)
port: 8123

##  Server name that will show up in commands and requests
server-name: 'Auto-Tune Test Server'

##  Automatic Pricing Model
pricing-model: 'Advanced'

##  Time Period in minutes
time-period: 10

##  The amount of menu rows in the GUI shop, value of 4-6.
menu-rows: 6

##  GUI Shop Menu title
menu-title: 'Auto-Tune Shop'

##  Message sent for players with no permission
no-permission: 'You do not have permission to perform this command'

##  -- Basic/Advanced Pricing Model Settings --  ##

##  Volatility Calulation Algorithim
##  Info: A fixed rate locks the maxiumum change to a certain price
##  Info: A variable rate changes the maxiumum price-change based on current price calculations
Volatility-Algorithim: 'Fixed'

##  Percentage difference in sell price to buy price
sell-price-difference: 2.5

##  Maximum Volatility per Time Period for the Fixed Volatility price calculation algorithim in economy units
Fixed-Max-Volatility: 2.00
##  Maximum Volatility per Time Period for the Fixed Volatility price calculation algorithim in economy units
Fixed-Max-Volatility: 2.00

##  Maximum Volatility per Time Period for the Variable Volatility price calculation algorithim as a percentage of total price
Variable-Max-Volatility: 6.00
##  Minimum Volatility per Time Period for the Fixed Volatility price calculation algorithim in economy units
Fixed-Min-Volatility: 0.05

##  -- Other Econonomy Settings --

##  Enable sell price difference variation to ease out sell price varition
sell-price-difference-variation-enabled: false
##  Starting percententage sell price difference for sell price varition
sell-price-differnence-variation-start: 25.0
##  Time in minutes until sell price reaches sell-price-difference set in pricing model settings (default 7 days)
sell-price-variation-time-period: 10080
##  Time in minutes that the sell-price-difference updates
##  Info: Must be a factor of sell-price-variation-time-period or it wont work!
sell-price-variation-update-period: 30



##  -- Other Settings --

##  Enable debug mode for more info on price calculations
debug-enabled: false

##  Enable ChecksumHeaderBypass if you have issues with data retrival or corruption
checksum-header-bypass: false