##################################################
###                                            ###
##########       <-- Auto-Tune -->       #########
###                                            ###
##################################################


main: unprotesting.com.github.Main
name: Auto-Tune
version: ${project.version}
author: Unprotesting
description: Automatic Economy Plugin
softdepend: [Vault]
api-version: 1.16
commands:
    at:
      description: Auto-Tune Command.
      usage: /<at> <login>
    trade:
      description: Trade Online with other players.
      usage: /<trade> 
    shop:
      description: GUIShop alias for buy and sell commands.
      usage: /<shop>
    sell:
      description: Sell items quickly to the shop.
      usage: /<sell>
    atadmin:
      description: Auto-Tune Admin Command.
      usage: /<atadmin> <skip>






