main: unprotesting.com.github.Main
name: Auto-Tune
version: 0.1.2
author: Unprotesting
description: Automatic Economy Plugin
softdepend: [Vault]
commands:
    at:
      description: Auto-Tune Command
      usage: /<at> <login>
    trade:
      description: Trade Online with other players
      usage: /<trade> 




