##################################################
###                                            ###
##########       <-- Auto-Tune -->       #########
###                                            ###
##################################################


main: unprotesting.com.github.Main
name: Auto-Tune
version: 0.2.1
author: Unprotesting
description: Automatic Economy Plugin
softdepend: [Vault]
api-version: 1.16
commands:
    at:
      description: Auto-Tune Command
      usage: /<at> <login>
    trade:
      description: Trade Online with other players
      usage: /<trade> 
    shop:
      description: GUIShop alias for buy and sell commands.
      usage: /<shop> 






