# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
        check-latest: true
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.2.0
      with:
        arguments: build test
        gradle-version: '7.4'
    - uses: actions/upload-artifact@v2
      with:
        name: 'Auto-Tune-Artifact'
        path: build/libs/*.jar
